/* Generated by the Nim Compiler v1.6.12 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}


function set_dark_mode() {
    if ((window.localStorage.getItem("theme") == "dark")) {
    document.body.classList.add("dark-theme");
    }
    else {
    document.body.classList.remove("dark-theme");
    }
    

  
}

function toggle_dark_mode() {
    if ((window.localStorage.getItem("theme") == "dark")) {
    window.localStorage.setItem("theme", "light");
    }
    else {
    window.localStorage.setItem("theme", "dark");
    }
    
    set_dark_mode();

  
}
