name: Build

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3

    - name: Set up Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        nim-version: stable

    - name: Run build
      run: nimble run

    - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
 