name: Build

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          nim-version: 1.6.12

      - name: Install dependencies
        run: nimble install -d -y

      - name: Build
        run: nimble make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
